<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Step extends \App\Entity\Step implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'stepBackgrounds', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'tools', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'nbQuestion', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'nbBackground'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'stepBackgrounds', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'tools', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'nbQuestion', '' . "\0" . 'App\\Entity\\Step' . "\0" . 'nbBackground'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Step $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive(bool $isActive): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(int $type): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getStepBackgrounds(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStepBackgrounds', []);

        return parent::getStepBackgrounds();
    }

    /**
     * {@inheritDoc}
     */
    public function addStepBackground(\App\Entity\StepBackground $stepBackground): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStepBackground', [$stepBackground]);

        return parent::addStepBackground($stepBackground);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStepBackground(\App\Entity\StepBackground $stepBackground): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStepBackground', [$stepBackground]);

        return parent::removeStepBackground($stepBackground);
    }

    /**
     * {@inheritDoc}
     */
    public function getTools(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTools', []);

        return parent::getTools();
    }

    /**
     * {@inheritDoc}
     */
    public function addTool(\App\Entity\Tool $tool): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTool', [$tool]);

        return parent::addTool($tool);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTool(\App\Entity\Tool $tool): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTool', [$tool]);

        return parent::removeTool($tool);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbQuestion(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbQuestion', []);

        return parent::getNbQuestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbQuestion(int $nbQuestion): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbQuestion', [$nbQuestion]);

        return parent::setNbQuestion($nbQuestion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbBackground(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbBackground', []);

        return parent::getNbBackground();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbBackground(int $nbBackground): \App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbBackground', [$nbBackground]);

        return parent::setNbBackground($nbBackground);
    }

}
