<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tool extends \App\Entity\Tool implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'question', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'step', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'possibleAnswers', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'stepBackground', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'questionNumber', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'questionImage'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'question', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'step', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'possibleAnswers', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'stepBackground', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'questionNumber', '' . "\0" . 'App\\Entity\\Tool' . "\0" . 'questionImage'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tool $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(int $type): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getStep(): ?\App\Entity\Step
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStep', []);

        return parent::getStep();
    }

    /**
     * {@inheritDoc}
     */
    public function setStep(?\App\Entity\Step $step): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStep', [$step]);

        return parent::setStep($step);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive(bool $isActive): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getPossibleAnswers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPossibleAnswers', []);

        return parent::getPossibleAnswers();
    }

    /**
     * {@inheritDoc}
     */
    public function addPossibleAnswer(\App\Entity\Answer $possibleAnswer): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPossibleAnswer', [$possibleAnswer]);

        return parent::addPossibleAnswer($possibleAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function removePossibleAnswer(\App\Entity\Answer $possibleAnswer): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePossibleAnswer', [$possibleAnswer]);

        return parent::removePossibleAnswer($possibleAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function getStepBackground(): ?\App\Entity\StepBackground
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStepBackground', []);

        return parent::getStepBackground();
    }

    /**
     * {@inheritDoc}
     */
    public function setStepBackground(?\App\Entity\StepBackground $stepBackground): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStepBackground', [$stepBackground]);

        return parent::setStepBackground($stepBackground);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestion', []);

        return parent::getQuestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestion($question)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestion', [$question]);

        return parent::setQuestion($question);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestionNumber(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestionNumber', []);

        return parent::getQuestionNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestionNumber(int $questionNumber): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestionNumber', [$questionNumber]);

        return parent::setQuestionNumber($questionNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestionImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestionImage', []);

        return parent::getQuestionImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestionImage(string $questionImage): \App\Entity\Tool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestionImage', [$questionImage]);

        return parent::setQuestionImage($questionImage);
    }

}
