<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7f3Zh3q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7f3Zh3q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7f3Zh3q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7f3Zh3q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7f3Zh3q\App_KernelDevDebugContainer([
    'container.build_hash' => '7f3Zh3q',
    'container.build_id' => '6065545d',
    'container.build_time' => 1626902511,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7f3Zh3q');
