<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/doc']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\ApiController::hello'], [], [['text', '/']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
    'web_own_login' => [[], ['_controller' => 'App\\Controller\\ApiController::login'], [], [['text', '/api/login']], [], []],
    'web_create_account' => [[], ['_controller' => 'App\\Controller\\ApiController::registerAccount'], [], [['text', '/app/create/account']], [], []],
    'api_validation_account' => [['token'], ['_controller' => 'App\\Controller\\ApiController::validateAccount'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/app/validation/account']], [], []],
    'api_update_password' => [[], ['_controller' => 'App\\Controller\\ApiController::updatePassword'], [], [['text', '/api/update/password']], [], []],
    'api_reset_password' => [[], ['_controller' => 'App\\Controller\\ApiController::resetPassword'], [], [['text', '/app/reset/password']], [], []],
    'api_get_current_user_info' => [[], ['_controller' => 'App\\Controller\\ApiController::getCurrentUserInfo'], [], [['text', '/api/user/info']], [], []],
    'api_list_user_session' => [[], ['_controller' => 'App\\Controller\\ApiController::listUserSession'], [], [['text', '/api/user/list/session']], [], []],
    'api_start_game' => [[], ['_controller' => 'App\\Controller\\ApiController::startGame'], [], [['text', '/api/start/game']], [], []],
    'api_leave_game' => [[], ['_controller' => 'App\\Controller\\ApiController::leaveGame'], [], [['text', '/api/leave/game']], [], []],
    'api_back_to_game' => [[], ['_controller' => 'App\\Controller\\ApiController::backGame'], [], [['text', '/api/back/to/game']], [], []],
    'api_answer_game_question' => [[], ['_controller' => 'App\\Controller\\ApiController::anwserToolQuestion'], [], [['text', '/api/answer/question']], [], []],
    'web_register_email' => [[], ['_controller' => 'App\\Controller\\ApiController::registerEmail'], [], [['text', '/api/register/email']], [], []],
];
