<?php

namespace ContainerYDt3fFH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcmeApi_Event_JwtDecodedListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'acme_api.event.jwt_decoded_listener' shared autowired service.
     *
     * @return \App\EventListener\JWTDecodedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/JWTDecodedListener.php';

        return $container->privates['acme_api.event.jwt_decoded_listener'] = new \App\EventListener\JWTDecodedListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), $container);
    }
}
