<?php

namespace Container7f3Zh3q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitSystemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'init_system' shared autowired service.
     *
     * @return \App\Service\SystemService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SystemService.php';

        return $container->services['init_system'] = new \App\Service\SystemService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), $container);
    }
}
