<?php

namespace Container7f3Zh3q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitSystemCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\InitSystemCommand' shared autowired service.
     *
     * @return \App\Command\InitSystemCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/InitSystemCommand.php';

        $container->privates['App\\Command\\InitSystemCommand'] = $instance = new \App\Command\InitSystemCommand($container);

        $instance->setName('app:init-system');

        return $instance;
    }
}
