<?php

namespace Container7f3Zh3q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMySerializerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\MySerializer' shared autowired service.
     *
     * @return \App\Service\MySerializer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MySerializer.php';

        return $container->services['App\\Service\\MySerializer'] = new \App\Service\MySerializer();
    }
}
